### ISSUE TITLE
Errors Loading Model with New Versions of Tensorflow

### ISSUE THREAD

**Issue by mgrover1** [mit-ll/unet-vda#1]
When reproducing the notebook, I ran into the following error in Cell 2:

```python-traceback
ValueError: You are trying to restore a checkpoint from a legacy Keras optimizer into a v2.11+ Optimizer, which can cause errors. Please update the optimizer referenced in your code to be an instance of `tf.keras.optimizers.legacy.Optimizer`, e.g.: `tf.keras.optimizers.legacy.Adam`.
```

Going through and installing tensorflow<2.11 solved the issue (after some environment troubleshooting). Would there be anyway to update this model to conform to newer versions?

Also - would you be interested in an environment file contribution?

**Comment by markveillette** [comment]
Gotta love tensorflow updates..    Thanks to @rcjackson for fixing this in https://github.com/mit-ll/unet-vda/pull/2

I'll also update the notebook to clarify that you can also load the model directly using `tf.keras.models.load_model`.   This way  is probably a little more robust to future TF updates..

**Comment by markveillette** [comment]
@mgrover1   yes, an env file would be great to add.   Go ahead and add one and I can test it.
